strains:
  - G2R10
  - E3R09
  - E3M18
  - D3R19
  - F2R14
  - m_1A01
  - E3R11_
  - A3R16
  - A1R12
  - A3M17
  - G2M07
  - m_3C02
  - A3R06
  - A3R12
  - E3R18
  - C2R09
  - A3R04
  - E3M09
  - I3M07
  - G2R14
  - D2M02
  - C3R12
  - m_3B05
  - D2R04
  - D2R05
  - F3R08
  - C3R15
  - C1M14
  - m_5C01
  - B3R10
  - G3M19
  - C3M10
  - F3M07_
  - E2M01
  - I2M19
  - m_3D05
  - C3M06
  - C1R06
  - B3M02
  - C3R17
  - F3M07
  - D2R18
  - m_6D03
  - m_4F10
  - F3R11
  - I2R16
  - B3R18
  - m_6D02
  - D2M19
  - m_4B03
  - A2M03
  - E3R01
  - B2M13
  - m_4A10
  - B2M06
  - m_6C06
  - E3M17
  - C2R02
  - B2M17
  - E3R11
  - C2M11
  - m_4E07
carbon_sources:
  - pro__L
  - glc__D
  - ac
  - cit
  - acgam
  - ser__D
  - rib__D
  - ile__L
  - cys__L
  - rmn
  - for
  - phe__L
  - f6p
  - trp__L
  - oaa
  - akg
  - r5p
  - met__L
  - 3pg
  - cyst__L
  - glu__D
  - icit
  - pep
  - pyr
media: data/media.yaml
models: data/strains/*.xml
parameters:
  no_objective: "--objective --feasible-solution"
  parsimony_only: "--objective --parsimony-only"
  growth_only: ""
  parsimony_growth: "--parsimony"
  all: "--parsimony"
tolerances:
  - 1e-6
  - 1e-7
  - 1e-8
