[project]
name = "misosoup-manuscript-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cobra>=0.29.1",
    "misosoup>=2.3.2",
    "snakemake>=9.8.2",
]
